### PR TITLE
Flag for forcing update from API endpoint.

### PR DESCRIPTION
**Pull request by xsve**
Added ability to force update from server (pass true to update_rates, default is false — same behaviour as before: updates rates only upon expiry).

### CODE REVIEW

**Comment by spk** [comment]
Hi @xsve i've just fixed build in https://github.com/spk/money-open-exchange-rates/pull/31 can you rebase this PR ?

**Comment by mcnelson** [comment]
As I just spent a day getting this gem to work for us, I have to ask, why not just call `save_rates`? When would you want to force an update without caching the result? At one point I wanted the functionality that this PR introduces, but realized `save_rates` does exactly that.

**Comment by xsve** [comment]
My intention was to provide a way to have a way to force rate updates,
before the cache expires.

I see now that calling save_rates and then update_rates will do just that.
I guess I was misled by the method name of save_rates.

Regards,
Sergei

**Comment by mcnelson** [comment]
Yeah, the API is a little confusing. The way we're doing it is calling `save_rates` every hour with new information. We don't call `update_rates` after that because we instead set `ttl_in_seconds`, which will reload your rates into memory as-needed from the cache when `get_rate` is called.

Based on my read, that was the intention behind the design of this gem. Hopefully that helps!

**Comment by spk** [comment]
This gem is an inspiration of other gem like https://github.com/RubyMoney/eu_central_bank#usage
I tried to keep same API

**Pull request closed without merging**
