### PR TITLE
Changed base api url

### PR DESCRIPTION
**Pull request by victor-cruz**
This PR should also fix https://github.com/spk/money-open-exchange-rates/issues/28

### CODE REVIEW

**Comment by leaniman** [comment]
👍

**Comment by avsh** [comment]
@victor-cruz, bump the gem version, plz

**Comment by spk** [comment]
Thanks released in [0.5.0](https://rubygems.org/gems/money-open-exchange-rates/versions/0.5.0)

**Comment by spk** [comment]
I did not get any notification for this change, did anyone get notification ?

**Comment by nikue** [comment]
Yes, I did.
Nikue Gardner

**Comment by victor-cruz** [comment]
I did't, but new api base path is documented here: https://docs.openexchangerates.org

**Pull request merged**
